import Head from 'next/head'
import {Hero} from './Components/Hero';
import {About} from './Components/About';
import{Skills} from './Components/Skills';
import {Projects} from './Components/Projects';
import {Contact} from './Components/Contact';
export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Hero/>
        <About/>
        <Skills/>
        <Projects/>
        <Contact/>
      </>
     
    </div>
  )
}
